### ISSUE TITLE
Case 2S.3 and T0 BGT

### ISSUE THREAD

**Issue by fish-on-land** [wookey-project/libiso7816#10]
Hi, I didn't find lib process "Case 2S.3 -- Process aborted; Ne not accepted, Na indicated",    it mapped 6C XX to the Response APDU directly. I think lib should  add hadling of this case.
Another question, I find some T0 card (some credit card, like PBOC, EMV card), can not work well if I do not add delay (here I used 16etus), between the leading edages of the start bits of the last character received and the first character sent in the opposite direction.  Although I find this principle in EMV book1 SPEC( EMV 4.2 book1 9.2.2.1 For the ICC or terminal, the minimum interval between the leading edges of thestart bits of the last character received and the first character sent in theopposite direction shall be 16 etus.), but I did not find in ISO7816 SPEC.

**Comment by rben-dev** [comment]
Hi,

Thanks for spotting the 2S.3 case issue: this was indeed missing and should be fixed in pull request https://github.com/wookey-project/libiso7816/pull/11

Regarding the 16 ETU delay asked by the EMV standard, this is indeed weird and not very clear. Some readers (see https://media.digikey.com/pdf/Data%20Sheets/NXP%20PDFs/TDA8007B_6.pdf) claim that BGT=16 must be applied when using T=0, while the ISO7816-3 standard only applies BGT for T=1 (with 22 ETU default value). In order to be compatible with EMV cards, I will try to implement such a delay when switching directions, but I will have to test that this does not break already tested cards. Weirdly, we have tested some EMV compatible cards and did not trigger the issue.

Would you accept to test a patch on your cards to check if everything is fine, and that the currently non-working EMV cards are OK? I will work on a pull request.

Regards,

**Comment by rben-dev** [comment]
Here it is : you can find an attempt to be EMV co compliant in the commit https://github.com/rb-anssi/libiso7816/commit/1d67788166fb8356af37b67fd7707a41ef4c8c9e on my fork of the lib (I'm waiting test results and confirmation that this does not break anything before triggering a pull request and merging this).

Would you please test this patch on your EMV co compliant cards?

Thanks for your feedback and help!
Reards,

**Comment by rben-dev** [comment]
Hi @fish-on-land,

Following our discussion, here is a new attempt to improve compatibility with case 2S.3, and also improve T=0 chaining with other corner cases:
https://github.com/rb-anssi/libiso7816/commit/0102faa37b14c23faa7a0f0e606ca83f38b04f22

After some reading and digging, I still think that "0x6cxx" is a "terminal state", meaning that any 0x61xx received after this command should be handled in the application layer. Namely, if we take case 2E.2 for example, when receiving a 0x6c (Case 2E.2 (b), page 38 of the standard) it is explicitly told to send the same command with proper length and "then the process shall be completed as described in case 2S.3". In case 2S.3, the response TPDU is explicitely mapped to the response APDU, meaning that it is indeed a "terminal state" of the T=0 receive automaton.

The patch is still untested on my side (and hopefully it doesn't break anything, sorry if it does), I will try to find some time to perform thorough tests on all my current T=0 compatible cards before creating a pull request on the upstream. I would be grateful if you could test the patch on your card, specifically the "wrong length" cases!

Thanks in advance for your feedback,
Regards,

**Comment by rben-dev** [comment]
The issue should be fixed with pull request #11
