### ISSUE TITLE
missing define of SC_ATR, SETUP_LENGTH, SC_APDU_cmd, SC_APDU_resp

### ISSUE THREAD

**Issue by fish-on-land** [wookey-project/libiso7816#5]
Hi, I am trying to use libiso7816 project, but found missing define of SC_ATR, SETUP_LENGTH, SC_APDU_cmd, SC_APDU_resp, can you fix it? 
Thanks a lot.

**Comment by rben-dev** [comment]
Hi,

Actually, you have to include the header "libs/smartcard/api/libsmartcard.h" when compiling libiso7816. This "cross-lib/cross-layer" mix is due to the way we abstract contact and contactless cards in the libsmartcard API of the WooKey project (contactless cards compatibility is future work, but hooks are present in the code to prepare this).

As a side note, please be aware that libiso7816 only contains the platform independent automatons of the ISO7816-3 standard for T=0 and T=1, meaning that you will have to provide a lower-level layer implementing the ISO7816 USART line (the API of this layer should be pretty straightforward) for this to work somewhere. In the WooKey project, this layer is provided by the ISO7816 driver in "drivers/socs/stm32f439/iso7816/": this driver implements the STM32F4 USART acceleration to handle the ISO line, and this is done on top of the EwoK kernel syscalls.

For your information, a standalone bare-metal implementation of the ISO7816-3 driver on the STM32F4 is provided in the LEIA project: https://github.com/cw-leia/cw-leia-standalone-firmware. The same libiso7816 is used on top of a bare-metal implementation of the USART driver (without the microkernel).

Regards,

**Comment by PThierry** [comment]
Hello,

As this is not an effective issue but the impact of a software architecture design (using a higher level smartcard abstraction for both contact and contact-less APIs), i'm closing this issue.

Nevertheless, don't hesitate to ask if you have some trouble in using the iso7816 software stack in your own environment :-)

**Comment by fish-on-land** [comment]
Thanks for the detail information, it does help me.
