### ISSUE TITLE
About WT calculate with TC2

### ISSUE THREAD

**Issue by fish-on-land** [wookey-project/libiso7816#6]
In libiso7816, calculate wi = atr->tc[1] & 0x0f,  but in SPEC 7816 it says TC2 encodes the waiting time integer WI over the eight bits, except the value '00' reserved for future use.
So should it be   if (atr->tc[1] != 0) wi = atr->tc[1]  ?
And another question, in SC_push_pull_APDU_T0( )  comments we send a 0 as P3 in a case 1 APDU, but code is send le byte,  it could be a mistake?

**Comment by rben-dev** [comment]
Hi,

Regarding TC2, you are perfectly right, the '00' value being reserved we should check it.

Regarding SC_push_pull_APDU_T0( ), actually the code works because in the case apdu->send_le is not set, apdu->le should be zero. However the comments are indeed intermixed and error prone! Thanks for the feedback :-)

These two points should be fixed in PR #7. Do not hesitate to provide us with other issues/typos regarding libiso7816, or issues you come across with actual smart cards!

Regards,

**Comment by fish-on-land** [comment]
Why TC2 only use lsb ( wi = atr->tc[1]&0x0f) , not full byte (wi = atr->tc[1]) ?

**Comment by rben-dev** [comment]
You are right, TC2 encodes WI over the eight bits, I missed it when moving code around!
Sorry for the typo when fixing the code and thanks for the follow up :-)

Regards,
